# Generated by Django 2.0.2 on 2018-03-06 04:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='条件')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_chains', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.IntegerField(default=None)),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='質問')),
                ('tags', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tags_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(default='', max_length=200)),
                ('question_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Question_upload')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='question_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Question_upload'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='question_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Question_upload'),
        ),
    ]
