# Generated by Django 2.0.2 on 2018-03-06 06:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypothesis',
            name='question_upload',
        ),
        migrations.RemoveField(
            model_name='question_upload',
            name='tags',
        ),
        migrations.AddField(
            model_name='question_upload',
            name='hypothesis',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='条件'),
        ),
        migrations.AlterField(
            model_name='question_upload',
            name='question',
            field=models.CharField(blank=True, max_length=200, verbose_name='質問'),
        ),
        migrations.DeleteModel(
            name='Hypothesis',
        ),
    ]
