# Generated by Django 2.0.2 on 2018-03-06 08:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20180306_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='条件')),
            ],
        ),
        migrations.RemoveField(
            model_name='question_upload',
            name='hypothesis',
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='question_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Question_upload'),
        ),
    ]
