# Generated by Django 2.0.2 on 2018-03-15 09:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20180308_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='para_chains',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='question_upload',
            name='types',
            field=models.CharField(choices=[('0', '算数または方程式'), ('1', '条件つき問題')], default='0', max_length=40),
        ),
    ]
