# Generated by Django 2.0.2 on 2018-03-20 08:51

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20180316_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypothesis',
            name='para_list',
            field=django_mysql.models.ListCharField(models.CharField(max_length=15), default=django.utils.timezone.now, max_length=200, size=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question_template',
            name='hardness',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
