# Generated by Django 2.0.2 on 2018-03-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20180320_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypothesis',
            name='para_list',
        ),
    ]
