# Generated by Django 2.0.2 on 2018-03-20 11:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_remove_question_edit_para_chains'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_edit',
            name='question_template',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='start', max_length=100, size=None),
            preserve_default=False,
        ),
    ]
