# Generated by Django 2.0.2 on 2018-03-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_question_edit_question_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_edit',
            new_name='Question_para',
        ),
        migrations.RenameField(
            model_name='question_para',
            old_name='question_template',
            new_name='para_chains',
        ),
    ]
