# Generated by Django 2.0.2 on 2018-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_auto_20180320_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_para',
            name='ans',
            field=models.TextField(default='answer'),
            preserve_default=False,
        ),
    ]
