# Generated by Django 2.0.2 on 2018-03-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0014_question_para_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_upload',
            name='types',
        ),
    ]
