# Generated by Django 2.0.2 on 2018-03-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0015_remove_question_upload_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_with_question', models.CharField(default='not defined', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge_point_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(default='数学', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question_upload',
            name='years_of_question',
            field=models.CharField(choices=[('p2', '小二'), ('p3', '小三'), ('p2', '小四'), ('p2', '小五'), ('p2', '小六')], default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='knowledge_point',
            name='question_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Question_upload'),
        ),
    ]
