# Generated by Django 2.0.2 on 2018-03-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0016_auto_20180326_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge_point_list',
            name='grade',
            field=models.CharField(default='小学', max_length=2),
        ),
    ]
