# Generated by Django 2.0.2 on 2018-03-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0017_knowledge_point_list_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_upload',
            name='years_of_question',
            field=models.CharField(choices=[('p2', '小二'), ('p3', '小三'), ('p2', '小四'), ('p2', '小五'), ('p2', '小六')], default='p5', max_length=2),
        ),
    ]
